clean:
	rm -fr .terraform* *tfstate*
ti:
	terraform init
tv:
	terraform validate
tp:
	terraform plan
ta:
	terraform apply
taa:
	terraform apply --auto-approve
td:
	terraform destroy
tdd:
	terraform destroy --auto-approve
