start:
	bash docker/bin/start.sh &
stop:
	bash docker/bin/stop.sh
restart: stop start
apish:
	bash docker/bin/apish.sh
mariadbsh:
	bash docker/bin/mariadbsh.sh
recreatedb:
	bash docker/bin/recreatedb.sh
test:
	bash docker/bin/testsh.sh
format:
	bash docker/bin/format.sh
lint:
	bash docker/bin/lint.sh
