start:
	bash docker/bin/start.sh &
stop:
	bash docker/bin/stop.sh
apish:
	bash docker/bin/apish.sh
mariadbsh:
	bash docker/bin/mariadbsh.sh
test:
	bash docker/bin/testsh.sh
format:
	bash docker/bin/format.sh
lint:
	bash docker/bin/lint.sh
