clean:
	rm -fr .terraform* *tfstate*
i:
	terraform init
v:
	terraform validate
p:
	terraform plan
a:
	terraform apply
aa:
	terraform apply --auto-approve
d:
	terraform destroy
da:
	terraform destroy --auto-approve
output:
	terraform output
docs:
	terraform-docs markdown table  --output-file=README.md .
