version: '3.3'
#----------------------------------------------------------
# definicion de la red y rango de ips 
#
# dbox project
#----------------------------------------------------------
networks:
    dbox-network:
        ipam:
            config:
                - subnet: 172.21.1.0/24
services:
    dbox.api:
        user:  "1000:1000"
        build: api
        container_name: 'dbox.api'
        ports:
          - 3000:3000
          - 4000:4000
          - 4431:443
        volumes:
            - ../api/:/var/www/vhosts/dbox/
        extra_hosts:
          - 'mariadb:172.21.1.12'
        hostname: dbox.api
        networks:
            dbox-network:
                ipv4_address: 172.21.1.14

    dbox.mariadb:
        build: mariadb
        container_name: 'dbox.mariadb'
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql
        restart: always
        hostname: dbox.mariadb
        networks:
            dbox-network:
                ipv4_address: 172.21.1.12