version: '3.3'
#----------------------------------------------------------
# definicion de la red y rango de ips 
#
# dbox project
#----------------------------------------------------------
networks:
    dbox-network:
        ipam:
            config:
                - subnet: 172.21.1.0/24
services:
    dbox.api:
        user:  "1000:1000"
        build: api
        container_name: 'dbox.api'
        ports:
          - 3000:3000
          - 4000:4000
          - 4431:443
        volumes:
            - ../api/:/var/www/vhosts/dbox/
        extra_hosts:
          - 'mariadb:172.21.1.12'
          - 'rabbitmq:172.21.1.13'
        hostname: dbox.api
        networks:
            dbox-network:
                ipv4_address: 172.21.1.14

    dbox.mariadb:
        build: mariadb
        container_name: 'dbox.mariadb'
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql
        restart: always
        hostname: dbox.mariadb
        networks:
            dbox-network:
                ipv4_address: 172.21.1.12
    #----------------------------------------------------------
    # servicio para mensajeria que podemos ver
    # via http en localhost:15672 guest/guest
    #
    # el dsn de conexion es: amqp://guest:guest@localhost:5672/
    #----------------------------------------------------------
    dbox.rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'dbox.rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - /var/lib/rabbitmq/
            - /var/log/rabbitmq
        hostname: dbox.rabbitmq
        networks:
            dbox-network:
                ipv4_address: 172.21.1.13